name: Check Image Using fixed version

on:
  pull_request:
    branches:
      - master

jobs:
  publish-notebook:
    name: Check Jupyter notebook image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Build spark_320_hadoop_322
        run: docker build -t ferlabcrsj/all-spark-notebook:3.1.2 .
        working-directory: spark_320_hadoop_322
