name: Publish Images Using fixed version

on:
  push:
    branches:
      - master

jobs:
  publish-notebook:
    name: Check Jupyter notebook image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log into registry
        run: echo "${{ secrets.FERLAB_DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.FERLAB_DOCKER_HUB_USER }} --password-stdin
      - name: Build image
        run: docker build -t ferlabcrsj/all-spark-notebook3.1.2 .
      - name: Push image
        run: docker push ferlabcrsj/all-spark-notebook:3.1.2
        working-directory: docker